RA-1814:Unnecessary imports should be removed
openmrs/openmrs-module-referenceapplication pull request #83
Opened 2020-09-18 13:27 UTC by Wandji69

2020-09-18 17:34 UTC, sacull commented
@Wandji69 In the description of the PR, it is worth providing a link to the ticket in JIRA. The person who will give opinions on the changes will know what ticket this PR applies to.

2020-09-18 17:36 UTC, sacull requested changes

2020-09-18 17:36 UTC, sacull commented on omod/src/test/java/org/openmrs/module/referenceapplication/page/controller/HomePageControllerTest.java
> +import static org.junit.Assert.*;
Try not to use wildcard import. Ref: https://wiki.openmrs.org/display/docs/Java+Conventions#JavaConventions-Imports

2020-09-23 16:11 UTC, sacull commented
You have not forgotten about this import: https://github.com/openmrs/openmrs-module-referenceapplication/blob/referenceapplication-2.10.0/omod/src/main/java/org/openmrs/module/referenceapplication/page/controller/HomePageController.java#L23 ;)

2020-09-24 13:30 UTC, sacull approved these changes
It looks good to me now. ;)

2020-09-24 13:34 UTC, Wandji69 commented
@sacull Thanks for reviewing.

2020-09-24 18:44 UTC, merged

2020-09-24 19:22 UTC, sacull commented
@Wandji69 You are probably ready to leave the introductory tickets and to take care of the more complex ones. ;)

2020-09-25 08:41 UTC, Wandji69 commented
> @Wandji69 You are probably ready to leave the introductory tickets and to take care of the more complex ones. ;)

Okay, thanks. I will round up with the tickets I have at hand before moving forward.